name: Sync Google Sheet CSV via API

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch: 

jobs:
  sync_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' 

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gspread pandas openpyxl 

    - name: Fetch Google Sheet CSV using Python script
      env:
        GOOGLE_SHEETS_API_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_API_CREDENTIALS }}
        
        GOOGLE_SHEET_ID: "18_qWTqGmvKum2P2l3UZy9lA9zxqMhJA5dT2Drq-e9hc" # 
      
        GOOGLE_SHEET_NAME: "Sheet1" 
        OUTPUT_CSV_PATH: "data/data.csv" 
      run: python fetch_sheet_data.py

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and push if changes exist
      run: |
      
        if [ ! -f "data/your_data.csv" ]; then
          echo "Error: data/your_data.csv was not created by the Python script."
          exit 1
        fi
        git add data/your_data.csv 
        if ! git diff-index --quiet HEAD; then
          git commit -m "Update data from Google Sheet (API) [skip ci]"
          git push
        else
          echo "No changes in CSV file. Skipping commit."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
